# Colors (kurokula)

[colors.bright]
black = '#141515'
blue = '#6890d7'
cyan = '#837369'
green = '#85b1a9'
magenta = '#887aa3'
red = '#b66056'
white = '#94959b'
yellow = '#dbbb43'

[colors.cursor]
cursor = '#702420'
text = '#fefbf3'

[colors.normal]
black = '#333333'
blue = '#2ab9ff'
cyan = '#9d5918'
green = '#54ca74'
magenta = '#9e60ec'
red = '#d23e08'
white = '#ddd0c4'
yellow = '#fff700'

[colors.primary]
background = '#141515'
foreground = '#ddd0c4'

[colors.selection]
background = '#515151'
text = '#ffc663'
