[colors]
background = '#141515'
foreground = '#ddd0c4'
selection-background = '#515151'
selection-foreground = '#ffc663'
cursor = '#702420'
black = '#333333'
red = '#d23e08'
green = '#54ca74'
yellow = '#fff700'
blue = '#2ab9ff'
magenta = '#9e60ec'
cyan = '#9d5918'
white = '#ddd0c4'
light_black = '#141515'
light_red = '#b66056'
light_green = '#85b1a9'
light_yellow = '#dbbb43'
light_blue = '#6890d7'
light_magenta = '#887aa3'
light_cyan = '#837369'
light_white = '#94959b'
